spring.application.name=chude2

server.port=8080

spring.datasource.url=jdbc:mysql://ballast.proxy.rlwy.net:30544/railway?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=QJsgFFlVkmMLfdrtrLRuEploarxVsyud

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
